# Generated by Django 2.2.8 on 2019-12-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineuser',
            name='timelines',
            field=models.ManyToManyField(blank=True, related_name='users', to='research.Meta'),
        ),
    ]
