/* eslint-disable */
require('./checked')
require('./circle')
require('./diamond')
require('./heptagon')
require('./hexagon')
require('./key')
require('./oval')
require('./polygon')
require('./square')
require('./star')
require('./star5')
require('./star8')
require('./triangle')
require('./unchecked')
