# Generated by Django 2.2.4 on 2019-08-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('url', models.URLField(blank=True, null=True)),
                ('book_or_article', models.CharField(blank=True, max_length=2000, null=True)),
                ('archived', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_short', models.CharField(blank=True, max_length=1000)),
                ('description_long', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('description_long', models.TextField(blank=True)),
                ('description_short', models.CharField(blank=True, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='research.Citation')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description_long', models.TextField(blank=True)),
                ('description_short', models.CharField(blank=True, max_length=800)),
                ('citation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='research.Citation')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='research.Image')),
                ('weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='research.Weight')),
            ],
        ),
    ]
