# Generated by Django 2.2.8 on 2019-12-12 22:27

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('caselaw_citation', models.CharField(blank=True, max_length=800, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('publication_title', models.CharField(blank=True, max_length=2000, null=True)),
                ('author_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('volume_number', models.IntegerField(blank=True, null=True)),
                ('issue_number', models.IntegerField(blank=True, null=True)),
                ('archived_url', models.URLField(blank=True, null=True)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('image', 'image'), ('caselaw', 'caselaw'), ('webpage', 'webpage'), ('article', 'article'), ('book', 'book')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description_long', models.TextField(blank=True)),
                ('description_short', models.CharField(blank=True, max_length=800)),
                ('hide', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('us', 'us'), ('world', 'world'), ('legislation', 'legislation'), ('caselaw', 'caselaw'), ('administrative', 'administrative')], max_length=100, null=True)),
                ('citation', models.ManyToManyField(blank=True, related_name='events', to='research.Citation')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('preceding_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='heads', to='research.Event')),
                ('succeeding_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tails', to='research.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(storage={'class': 'FileSystemStorage', 'kwargs': {'location': '/Users/anastasia/timeline/timeline/db-files/images'}}, upload_to='')),
                ('src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='research.Citation')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='research.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_short', models.CharField(blank=True, max_length=1000)),
                ('description_long', models.TextField(blank=True)),
                ('events', models.ManyToManyField(blank=True, to='research.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(blank=True, to='research.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='research.Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='events', to='research.Theme'),
        ),
        migrations.AddField(
            model_name='event',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='research.Weight'),
        ),
    ]
