# Generated by Django 2.2.8 on 2019-12-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeline',
            field=models.ForeignKey(default='us-immigration', on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='events', to='research.Meta'),
            preserve_default=False,
        ),
    ]
