# Generated by Django 2.2.4 on 2019-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190819_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='research.Tag'),
        ),
    ]
