# Generated by Django 2.2.4 on 2019-08-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20190819_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='archived',
            new_name='archived_url',
        ),
        migrations.AddField(
            model_name='citation',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
