# Generated by Django 2.2.8 on 2020-01-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20191216_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='citations', to='research.Meta'),
        ),
        migrations.AddField(
            model_name='group',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='research.Meta'),
        ),
    ]
