# Generated by Django 2.2.4 on 2019-08-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20190819_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='cite',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('caselaw', 'caselaw'), ('webpage', 'webpage'), ('article', 'article'), ('book', 'book')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='keyevent',
            name='citations',
            field=models.ManyToManyField(blank=True, to='research.Citation'),
        ),
    ]
