# Generated by Django 2.2.4 on 2019-08-23 16:00
import os
from django.db import migrations, models
from timeline.settings import BASE_DIR

class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20190820_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('us_event', 'us_event'), ('international_event', 'international_event'), ('legislature', 'legislature'), ('caselaw', 'caselaw')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='events',
            field=models.ManyToManyField(blank=True, to='research.Event'),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.FileField(storage={'class': 'FileSystemStorage', 'kwargs': {'location': os.path.join(BASE_DIR, 'db-files/images')}}, upload_to=''),
        ),
        migrations.DeleteModel(
            name='KeyEvent',
        ),
    ]
