# Generated by Django 2.2.8 on 2020-01-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_region_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='themes', to='research.Meta'),
        ),
    ]
