# Generated by Django 2.2.4 on 2019-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20190823_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('us_event', 'us_event'), ('international_event', 'international_event'), ('legislation', 'legislation'), ('caselaw', 'caselaw')], max_length=100, null=True),
        ),
    ]
