# Generated by Django 2.2.8 on 2020-01-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20200116_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='new_type',
            new_name='type',
        ),
    ]
