# Generated by Django 2.2.8 on 2020-01-23 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_auto_20200116_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='meta',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
