# Generated by Django 2.2.4 on 2019-09-11 02:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_auto_20190910_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
