# Generated by Django 2.2.8 on 2020-01-30 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('research', '0011_auto_20200123_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='color',
            field=models.CharField(blank=True,
                                   choices=[('darkgreen', 'darkgreen'), ('blue', 'blue'), ('crimson', 'crimson'),
                                            ('lavender', 'lavender'), ('green', 'green'), ('gold', 'gold'),
                                            ('orange', 'orange'), ('pink', 'pink'), ('navy', 'navy')],
                                   help_text='Color for event type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='end_year',
            field=models.IntegerField(blank=True, help_text='Last year that can show in the timeline', null=True,
                                      validators=[django.core.validators.MaxValueValidator(2100),
                                                  django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='meta',
            name='published',
            field=models.BooleanField(default=False, help_text='Set this field to true to show timeline on site.'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='start_year',
            field=models.IntegerField(blank=True, help_text='First year that can show in the timeline', null=True,
                                      validators=[django.core.validators.MaxValueValidator(2100),
                                                  django.core.validators.MinValueValidator(1000)]),
        ),
    ]
