# Generated by Django 2.2.4 on 2019-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_auto_20191104_1657'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='event',
            name='citation',
        ),
        migrations.AddField(
            model_name='event',
            name='citation',
            field=models.ManyToManyField(blank=True, related_name='events', to='research.Citation'),
        ),
    ]
