# Generated by Django 2.2.4 on 2019-11-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_auto_20191104_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='relationships',
        ),
    ]
