# Generated by Django 2.2.4 on 2019-11-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0017_remove_event_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='political_dissidents',
            field=models.BooleanField(default=False),
        ),
    ]
