# Generated by Django 2.2.4 on 2019-11-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_event_political_dissidents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('us', 'us'), ('world', 'world'), ('legislation', 'legislation'), ('caselaw', 'caselaw'), ('administrative', 'administrative')], max_length=100, null=True),
        ),
    ]
