# Generated by Django 2.2.4 on 2019-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0020_auto_20191127_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
