# Generated by Django 2.2.8 on 2019-12-12 18:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0021_theme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
